"""Generate the README tool reference table from the server's list_tools().

Usage: python scripts/gen_tool_docs.py [--check]
"""

import argparse
import asyncio
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
README = ROOT / "README.md"
START = "<!-- tools:start (generated by scripts/gen_tool_docs.py; do not edit) -->"
END = "<!-- tools:end -->"


def hint(annotations, camel):
    snake = "".join("_" + c.lower() if c.isupper() else c for c in camel)
    value = getattr(annotations, camel, None)
    return getattr(annotations, snake, None) if value is None else value


async def listed_tools(writes=True):
    sys.path.insert(0, str(ROOT / "src"))
    from nvidia_mcp.config import Config
    from nvidia_mcp.server import create_server

    with tempfile.TemporaryDirectory() as state:
        mcp, ops = create_server(Config(host="127.0.0.1", state=Path(state), allow_writes=writes))
        try:
            result = await mcp.list_tools()
        finally:
            ops.t.close()
    return getattr(result, "tools", result)


def table(tools, read_only_names):
    rows = [
        "| Tool | Title | Access | What it does |",
        "| --- | --- | --- | --- |",
    ]
    for tool in sorted(tools, key=lambda t: t.name):
        a = tool.annotations
        if tool.name not in read_only_names:
            access = "write mode"
        elif hint(a, "readOnlyHint"):
            access = "read-only"
        else:
            access = "no TV changes"
        description = " ".join((tool.description or "").split()).replace("|", "\\|")
        title = hint(a, "title") or tool.name
        rows.append(f"| `{tool.name}` | {title} | {access} | {description} |")
    return "\n".join(rows)


def render(text, generated):
    if START not in text or END not in text:
        raise SystemExit("README.md is missing the tool table markers")
    head, rest = text.split(START, 1)
    _, tail = rest.split(END, 1)
    return f"{head}{START}\n{generated}\n{END}{tail}"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if README.md is stale")
    args = parser.parse_args()
    text = README.read_text(encoding="utf-8")
    always = {t.name for t in asyncio.run(listed_tools(writes=False))}
    updated = render(text, table(asyncio.run(listed_tools()), always))
    if args.check:
        if updated != text:
            raise SystemExit("README tool table is stale: run python scripts/gen_tool_docs.py")
        print("README tool table is up to date")
        return
    README.write_text(updated, encoding="utf-8")
    print("Updated README tool table")


if __name__ == "__main__":
    main()
